### ISSUE TITLE
Props를 관리한다.

### ISSUE THREAD

**Issue by warmwhiten** [KTPT/Quna-client#13]
### 상세 내용
Props를 관리한다.

### 선행 작업
X

### 기능 목록
- [x] props type 관련 문서 댓글로 공유하기
- [x] 적용하기

**Comment by toneyparky** [comment]
단톡방에서 이야기나눈대로 따로 pr을 파지 않고 커밋을 하여 바로 [develop 브랜치에 머지](https://github.com/KTPT/Quna-client/commit/ce63c7bdc8a631dd6837db450231aa52c4d663a1)했습니다.

## 내용 설명 
- mob 프로그래밍을 하며 `/types/model.ts`라는 곳에 `AnswerModel`과 `QuestionModel`을 만들었는데 이를 사용하는 `/components/lib/answers.tsx`와 `/components/lib/questions`에서 mob 프로그래밍 이전에 만들어준 `AnswerDetailProps`와 `QuestionDetailProps`를 참조했기에 `/pages/questions/[id].tsx`에서 데이터를 불러오지 못하는 상황이 발생했습니다.

### 예시 코드
~~~typescript
// /types/model.ts : [id].tsx에 뿌려줄 데이터 형태 interface

export interface AnswerModel {
  id: number;
  questionId: number;
  contents: string;
  responderId: number | null;
  createdAt: string;
  lastModifiedAt: string;
}

export interface QuestionModel {
  id: number;
  title: string;
  contents: string;
  responderId: number | null;
  createdAt: string;
  lastModifiedAt: string;
}

~~~
